spring:
  application:
    name: salesflow
  datasource:
    url: jdbc:postgresql://localhost:5432/salesflow
    username: postgres
    password: Cpp#1501
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: leonardosilvalls1908@gmail.com
    password: jrnj qajx cqad uqez
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true